name: Move app folder to root
on:
  workflow_dispatch:
  push:
    paths:
      - 'app/**'
jobs:
  move:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Move files from app/ to root
        run: |
          shopt -s dotglob
          mv app/* . || echo "Folder app kosong/ga ada"
          rm -rf app || echo "Folder app udah kehapus"
      - name: Push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Move app contents to root 🗿" || exit 0
          git push
