name: Move app to root
on: workflow_dispatch  # biar bisa jalan manual
jobs:
  move:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Pindahin isi app ke root
        run: |
          shopt -s dotglob
          mv app/* . 
          rm -rf app
          
      - name: Push hasil pindah
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Move app contents to root 🗿" || exit 0
          git push
